/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#ifndef _NO_DBUS 
#ifndef _SENSOR_DBUSCLIENT_H_
#define _SENSOR_DBUSCLIENT_H_

#include <Poco/SharedPtr.h>
#include <Poco/BasicEvent.h>
#include <Poco/Exception.h>
#include <string>
#include <string.h>
#include <vector>
#include <map>
#include <memory>
#include <dbus-c++/dbus.h>
#include <dbus/dbus-protocol.h>
///includes
#include "BB/Services/Sensor.h"


namespace TBS { 
	namespace BB { 
		namespace Services { 
			namespace Sensor { 
				namespace Stub { 
       class DataCollector_DBusClient : public ::DBus::InterfaceProxy, public TBS::BB::Services::Sensor::IDataCollector {
			public:
				typedef Poco::SharedPtr <DataCollector_DBusClient> Ptr;
				
				DataCollector_DBusClient() : ::DBus::InterfaceProxy("com.TBS.BB.Services.Sensor.DataCollector"){
					
				}
				virtual ~DataCollector_DBusClient() {
				}

				
				static const std::string & dbuspath(){ static std::string val = "/com/TBS/BB/Services/Sensor"; return val; }
				static const std::string & dbusname(){ static std::string val = "com.TBS.BB.Services.Sensor.DataCollector"; return val; }
				
				
 //methods 
				virtual void SendSensorData(const std::string & sensorType, const std::string & sensorName, const std::string & sensorUnit, const std::string & sensorDate, const int32_t & sensorStatus, const double & sensorValue, const std::string & sensorTextValue){		try {
		::DBus::CallMessage call;
		::DBus::MessageIter wi = call.writer();

		wi << sensorType;
		wi << sensorName;
		wi << sensorUnit;
		wi << sensorDate;
		wi << sensorStatus;
		wi << sensorValue;
		wi << sensorTextValue;
		call.member("SendSensorData");
		::DBus::Message ret = invoke_method (call);
		} catch (::DBus::Error & err){
			if (strcmp(err.name(), DBUS_ERROR_FAILED) == 0){
				throw ::TBS::Services::RuntimeServiceException(err.message());
			} else {
				throw ::TBS::Services::ChannelServiceException(err.what());
			}
		}
	}


		private: 
				
			};
 } 
 } 
 } 
 } 
 } 


namespace TBS { 
	namespace BB { 
		namespace Services { 
			namespace Sensor { 
				namespace Stub { 
       class DataDistributor_DBusClient : public ::DBus::InterfaceProxy, public TBS::BB::Services::Sensor::IDataDistributor {
			public:
				typedef Poco::SharedPtr <DataDistributor_DBusClient> Ptr;
				
				DataDistributor_DBusClient() : ::DBus::InterfaceProxy("com.TBS.BB.Services.Sensor.DataDistributor"){
							connect_signal(DataDistributor_DBusClient, SensorDataReceived, _SensorDataReceived_sigstub);

				}
				virtual ~DataDistributor_DBusClient() {
				}

				
				static const std::string & dbuspath(){ static std::string val = "/com/TBS/BB/Services/Sensor"; return val; }
				static const std::string & dbusname(){ static std::string val = "com.TBS.BB.Services.Sensor.DataDistributor"; return val; }
				
				
 //methods 
				
		private: 
					void _SensorDataReceived_sigstub(const ::DBus::SignalMessage &sig){
		::DBus::MessageIter ri = sig.reader();

		std::string _sensorType;
		ri >> _sensorType;
		std::string _sensorName;
		ri >> _sensorName;
		std::string _sensorUnit;
		ri >> _sensorUnit;
		std::string _sensorDate;
		ri >> _sensorDate;
		int32_t _sensorStatus;
		ri >> _sensorStatus;
		double _sensorValue;
		ri >> _sensorValue;
		std::string _sensorTextValue;
		ri >> _sensorTextValue;
		SensorDataReceivedArg sig_arg;
		sig_arg.sensorType = _sensorType;
		sig_arg.sensorName = _sensorName;
		sig_arg.sensorUnit = _sensorUnit;
		sig_arg.sensorDate = _sensorDate;
		sig_arg.sensorStatus = _sensorStatus;
		sig_arg.sensorValue = _sensorValue;
		sig_arg.sensorTextValue = _sensorTextValue;

		//raise poco event
		SensorDataReceived(this, sig_arg);
	}

			};
 } 
 } 
 } 
 } 
 } 



#endif //_SENSOR_DBUSCLIENT_H_
#endif

