/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#ifndef _VISUALIZATION_JSONSERVER_H_
#define _VISUALIZATION_JSONSERVER_H_

#include <Poco/SharedPtr.h>
#include <Poco/BasicEvent.h>
#include <string>
#include <vector>
#include <map>
#include <memory>
#include <jsonrpc/rpc.h>
///includes
#include "BB/Services/Visualization.h"


namespace TBS { 
	namespace BB { 
		namespace Visualization { 
			namespace Stub { 
	class Query_JsonServer : public jsonrpc::AbstractServerInterface<Query_JsonServer>
		{
			public:
				Query_JsonServer(jsonrpc::ServiceHandlers & handlers, TBS::BB::Visualization::IQuery::Ptr interfaceImpl) :
					jsonrpc::AbstractServerInterface<Query_JsonServer>("TBS.BB.Visualization.Query", handlers), interfaceImpl(interfaceImpl) 
					{
						            this->bindAndAddMethod(new jsonrpc::Procedure("GetSensors", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_ARRAY,  NULL), &Query_JsonServer::GetSensorsI);
            this->bindAndAddMethod(new jsonrpc::Procedure("GetSensorData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_ARRAY, "sensorType",jsonrpc::JSON_STRING,"sensorName",jsonrpc::JSON_STRING, NULL), &Query_JsonServer::GetSensorDataI);
            this->bindAndAddMethod(new jsonrpc::Procedure("GetSensorsData", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_ARRAY, "sensorType",jsonrpc::JSON_STRING, NULL), &Query_JsonServer::GetSensorsDataI);

					}
					
					        inline virtual void GetSensorsI(const ::Json::Value& request, ::Json::Value& response) 
        {
            response = jsonrpc::Convertor::cpp2Json< std::vector< SensorInfo > >(this->GetSensors());
        }

        inline virtual void GetSensorDataI(const ::Json::Value& request, ::Json::Value& response) 
        {
            response = jsonrpc::Convertor::cpp2Json< std::vector< SensorData > >(this->GetSensorData(jsonrpc::Convertor::json2Cpp< std::string >(request["sensorType"]), jsonrpc::Convertor::json2Cpp< std::string >(request["sensorName"])));
        }

        inline virtual void GetSensorsDataI(const ::Json::Value& request, ::Json::Value& response) 
        {
            response = jsonrpc::Convertor::cpp2Json< std::vector< SensorData > >(this->GetSensorsData(jsonrpc::Convertor::json2Cpp< std::string >(request["sensorType"])));
        }


					        std::vector< SensorInfo > GetSensors(){
        	return interfaceImpl->GetSensors();
        }

        std::vector< SensorData > GetSensorData(const std::string & sensorType, const std::string & sensorName){
        	return interfaceImpl->GetSensorData(sensorType, sensorName);
        }

        std::vector< SensorData > GetSensorsData(const std::string & sensorType){
        	return interfaceImpl->GetSensorsData(sensorType);
        }


			private:
				TBS::BB::Visualization::IQuery::Ptr interfaceImpl;
};
 } 
 } 
 } 
 } 



#endif //_VISUALIZATION_JSONSERVER_H_

