/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#ifndef _VISUALIZATION_SERVICE_JSON_H_
#define _VISUALIZATION_SERVICE_JSON_H_

#include <Poco/SharedPtr.h>
#include <Poco/BasicEvent.h>
#include <string>
#include <vector>
#include <map>
#include <memory>
#include <TBS/Services/Services.h>
#include <TBS/Services/Json/JsonServices.h>
///includes
#include "BB/Services/Visualization.h"


namespace TBS { 
	namespace BB { 
		namespace Visualization { 
			namespace Json { 
       class Client {
			public:
				typedef Poco::SharedPtr <Client> Ptr;
				
				Client(const TBS::Services::JsonClientChannel & ch);
				
				
 //methods 
				TBS::BB::Visualization::IQuery & Query();

				
		private: 
				TBS::Services::JsonClientChannel ch;
				TBS::BB::Visualization::IQuery::Ptr query_;

			};
			
			
		class Server {
			public:
				typedef Poco::SharedPtr<Server> Ptr;
				Server(const TBS::Services::JsonServerChannel & ch);
				
				void start();
				void stop();
			public:
				TBS::Services::IServer::Ptr createQuery(TBS::BB::Visualization::IQuery::Ptr impl);

				
			private:
				TBS::Services::ICommChannelHolder::Ptr channel;
		};
 } 
 } 
 } 
 } 

#endif //_VISUALIZATION_SERVICE_H_

