#! /usr/bin/python2

import os
import sys
import subprocess

git_root = os.getcwd()
script_name = "tbs.b2.py"

while not os.path.isfile(os.path.join(git_root, script_name)):
	next_git_root = os.path.dirname(git_root)
	if next_git_root == git_root:
		print "tbs.b2.py not found in current or any parent directory"
		sys.exit(-1)
	git_root = next_git_root

params = sys.argv[1:]
rc = subprocess.call([os.path.join(git_root, script_name)]+params, env=os.environ)
sys.exit(rc)

