/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */

function Query(params){
  var settings = {
      url: params.url + "TBS.BB.Visualization.Query",
  };
  
  
 //methods 
          this.GetSensors = function(){
			return $.ajax({
    			url: settings.url,
    			jsonp: "callback",
    			dataType: "jsonp",
    			data: {
    				method: "GetSensors"
				}
			});
		};
        this.GetSensorData = function(_sensorType, 
_sensorName){
			return $.ajax({
    			url: settings.url,
    			jsonp: "callback",
    			dataType: "jsonp",
    			data: {
    				method: "GetSensorData",
sensorType: _sensorType, 
sensorName: _sensorName
				}
			});
		};
        this.GetSensorsData = function(_sensorType){
			return $.ajax({
    			url: settings.url,
    			jsonp: "callback",
    			dataType: "jsonp",
    			data: {
    				method: "GetSensorsData",
sensorType: _sensorType
				}
			});
		};

}



