/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */

function Query(params){
  var settings = {
      url: params.url + "TBS.BB.WebUI.Query",
  };
  
  
 //methods 
          this.GetSensors = function(){
			return $.ajax({
    			url: settings.url,
    			jsonp: "callback",
    			dataType: "jsonp",
    			data: {
    				method: "GetSensors"
				}
			});
		};
        this.GetSensorData = function(_sensorType, 
_sensorName){
			return $.ajax({
    			url: settings.url,
    			jsonp: "callback",
    			dataType: "jsonp",
    			data: {
    				method: "GetSensorData",
sensorType: _sensorType, 
sensorName: _sensorName
				}
			});
		};
        this.GetSensorsData = function(_sensorType){
			return $.ajax({
    			url: settings.url,
    			jsonp: "callback",
    			dataType: "jsonp",
    			data: {
    				method: "GetSensorsData",
sensorType: _sensorType
				}
			});
		};

}

function Configuration(params){
  var settings = {
      url: params.url + "TBS.BB.WebUI.Configuration",
  };
  
  
 //methods 
          this.SetSensorProperty = function(_sensorType, 
_sensorRawName, 
_sensorProperty, 
_sensorValue){
			return $.ajax({
    			url: settings.url,
    			jsonp: "callback",
    			dataType: "jsonp",
    			data: {
    				method: "SetSensorProperty",
sensorType: _sensorType, 
sensorRawName: _sensorRawName, 
sensorProperty: _sensorProperty, 
sensorValue: _sensorValue
				}
			});
		};

}



