/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#ifndef _WEBUI_SERVICE_JSON_H_
#define _WEBUI_SERVICE_JSON_H_

#include <Poco/SharedPtr.h>
#include <Poco/BasicEvent.h>
#include <string>
#include <vector>
#include <map>
#include <memory>
#include <TBS/Services/Services.h>
#include <TBS/Services/Json/JsonServices.h>
///includes
#include "BB/Services//WebUI.h"


namespace TBS { 
	namespace BB { 
		namespace WebUI { 
			namespace Json { 
       class GEN_SERVICE_API Client {
			public:
				typedef Poco::SharedPtr <Client> Ptr;
				
				Client(const TBS::Services::JsonClientParams & ch);
				~Client();
				
				
 //methods 
				TBS::BB::WebUI::IQuery & Query();
TBS::BB::WebUI::IConfiguration & Configuration();

				
		private: 
				TBS::Services::JsonClientParams ch;
				TBS::BB::WebUI::IQuery::Ptr query_;
TBS::BB::WebUI::IConfiguration::Ptr configuration_;

			};
			
			
		class GEN_SERVICE_API Server {
			public:
				typedef Poco::SharedPtr<Server> Ptr;
				
				static Server::Ptr createJsonServer(const TBS::Services::JsonServerParams & p);
				static Server::Ptr createJsonpServer(const TBS::Services::JsonServerParams & p);
				static Server::Ptr createWsServer(const TBS::Services::JsonServerParams & p);
				static Server::Ptr createRawServer(const TBS::Services::JsonServerParams & p);
				
				~Server();
				
				void start();
				void stop();
			public:
				TBS::Services::IServer::Ptr createQuery(TBS::BB::WebUI::IQuery::Ptr impl);
TBS::Services::IServer::Ptr createConfiguration(TBS::BB::WebUI::IConfiguration::Ptr impl);

				
			private:
				Server(TBS::Services::ICommChannelHolder::Ptr ch);
				TBS::Services::ICommChannelHolder::Ptr channel;
		};
 } 
 } 
 } 
 } 

#endif //_WEBUI_SERVICE_H_

