/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#include "TBS/Services/Introspection.h"
#include "BB/Services/Visualization.h"



namespace TBS { 
	namespace BB { 
		namespace Visualization { 
		::TBS::Services::Introspection::Class __introspectionIQuery(){
			::TBS::Services::Introspection::Namespace cnmspc;
cnmspc.push_back("TBS");
cnmspc.push_back("BB");
cnmspc.push_back("Visualization");
::TBS::Services::Introspection::Class c("TBS.BB.Visualization.Query", "Query", cnmspc,"");
{
	::TBS::Services::Introspection::Method m("GetSensors", "");
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("sensors", "a[SensorInfo]", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("GetSensorData", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorType", "s", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorName", "s", ""));
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("sensorData", "a[SensorData]", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("GetSensorsData", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorType", "s", ""));
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("allSensorData", "a[SensorData]", ""));
	c.methods.push_back(m);
}
return c;

		}
	   const ::TBS::Services::Introspection::Class & IQuery::introspection(){
			static ::TBS::Services::Introspection::Class c(__introspectionIQuery());
			return c;
	   }
 } 
 } 
 } 




