/**
 * THIS FILE IS GENERATED BY genTool, DO NOT CHANGE IT!!!!!
 */
#include "TBS/Services/Introspection.h"
#include "BB/Services//WebUI.h"



namespace TBS { 
	namespace BB { 
		namespace WebUI { 
		::TBS::Services::Introspection::Class __introspectionIQuery(){
			::TBS::Services::Introspection::Namespace cnmspc;
cnmspc.push_back("TBS");
cnmspc.push_back("BB");
cnmspc.push_back("WebUI");
::TBS::Services::Introspection::Class c("TBS.BB.WebUI.Query", "Query", cnmspc,"");
{
	::TBS::Services::Introspection::Method m("GetSensors", "");
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("sensors", "a[SensorInfo]", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("GetSensorData", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorType", "s", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorName", "s", ""));
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("sensorData", "a[SensorData]", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("ClearSensorData", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorType", "s", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorName", "s", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("GetSensorsData", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorType", "s", ""));
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("allSensorData", "a[SensorData]", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("GetRuntimeStatus", "");
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("status", "a[RuntimeStatus]", ""));
	c.methods.push_back(m);
}
return c;

		}
	   const ::TBS::Services::Introspection::Class & IQuery::introspection(){
			static ::TBS::Services::Introspection::Class c(__introspectionIQuery());
			return c;
	   }
 } 
 } 
 } 


namespace TBS { 
	namespace BB { 
		namespace WebUI { 
		::TBS::Services::Introspection::Class __introspectionIConfiguration(){
			::TBS::Services::Introspection::Namespace cnmspc;
cnmspc.push_back("TBS");
cnmspc.push_back("BB");
cnmspc.push_back("WebUI");
::TBS::Services::Introspection::Class c("TBS.BB.WebUI.Configuration", "Configuration", cnmspc,"");
{
	::TBS::Services::Introspection::Method m("GetSensorProperties", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorType", "s", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorRawName", "s", ""));
  m.outArguments.push_back(::TBS::Services::Introspection::Argument("sensorProperty", "a[SensorProperty]", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("SetSensorProperty", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorType", "s", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorRawName", "s", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorPropertyName", "s", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("sensorPropertyValue", "s", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("SetRuntimeStatus", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("status", "s", ""));
	c.methods.push_back(m);
}
{
	::TBS::Services::Introspection::Method m("SendTask", "");
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("what", "s", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("params", "s", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("from", "s", ""));
  m.inArguments.push_back(::TBS::Services::Introspection::Argument("to", "s", ""));
	c.methods.push_back(m);
}
return c;

		}
	   const ::TBS::Services::Introspection::Class & IConfiguration::introspection(){
			static ::TBS::Services::Introspection::Class c(__introspectionIConfiguration());
			return c;
	   }
 } 
 } 
 } 




